acme_child:
    resource: "@AcmeChildBundle/Resources/config/routing.yml"
    prefix:   /

acme_parent:
    resource: "@AcmeParentBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
