parameters:
#    acme_parent.example.class: Acme\ParentBundle\Example

services:
#    acme_parent.example:
#        class: %acme_parent.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
