parameters:
#    acme_child.example.class: Acme\ChildBundle\Example

services:
#    acme_child.example:
#        class: %acme_child.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
